apiVersion: v1
kind: Secret
metadata:
  name: chat-gpt-bot-env
type: Opaque
stringData:
  SLACK_BOT_TOKEN: "your_bot_token_here"
  SLACK_APP_TOKEN: "your_app_token_here"
  OPENAI_API_KEY: "your_api_key_here"
  # Optional: gpt-3.5-turbo and gpt-4 are currently supported (default: gpt-3.5-turbo)
  OPENAI_MODEL: "gpt-3.5-turbo"
  # Optional: You can adjust the timeout seconds for OpenAI calls (default: 30)
  OPENAI_TIMEOUT_SECONDS: 60
  # Optional: You can include priming instructions for ChatGPT to fine tune the bot purpose
  OPENAI_SYSTEM_TEXT: ""
  # Optional: When the string is "true", this app translates ChatGPT prompts into a user's preferred language (default: true)
  USE_SLACK_LANGUAGE: false
  # Optional: Adjust the app's logging level (default: DEBUG)
  SLACK_APP_LOG_LEVEL: DEBUG
  # Optional: When the string is "true", translate between OpenAI markdown and Slack mrkdwn format (default: false)
  TRANSLATE_MARKDOWN: true
