apiVersion: v1
kind: Pod
metadata:
  name: chat-gpt-bot-pod
spec:
  containers:
  - name: chat-gpt-bot-container
    image: 781124778026.dkr.ecr.eu-west-1.amazonaws.com/yap/hackday/ai:prod
    envFrom:
    - secretRef:
        name: chat-gpt-bot-env
